{
  parserClass="com.enterscript.noX3LanguagePlugin.language.parser.NOX3Parser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Bnf"
  psiImplClassSuffix="Impl"

  psiPackage="com.enterscript.noX3LanguagePlugin.language.psi"
  psiImplPackage="com.enterscript.noX3LanguagePlugin.language.psi.impl"

  elementTypeHolderClass="com.enterscript.noX3LanguagePlugin.language.psi.NOX3Types"

  elementTypeClass="com.enterscript.noX3LanguagePlugin.language.psi.NOX3ElementType"
  tokenTypeClass="com.enterscript.noX3LanguagePlugin.language.psi.NOX3TokenType"


  tokens = [
      OP_EQ="="
      OP_IS="::="
      OP_OR="|"
      OP_OPT="?"
      OP_ONEMORE="+"
      OP_ZEROMORE="*"
      OP_AND="&"
      OP_NOT="!"
      SEMICOLON=";"
      LEFT_BRACE="{"
      RIGHT_BRACE="}"
      LEFT_BRACKET="["
      RIGHT_BRACKET="]"
      LEFT_PAREN="("
      RIGHT_PAREN=")"
      EXTERNAL_START="<<"
      EXTERNAL_END=">>"

      space='regexp:\s+'
      id="regexp:\w+"
      string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"
      number="regexp:\d+"
      line_comment="regexp://.*"
      block_comment="regexp:/\*(.|\n)*\*/"
    ]

}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY