{
  parserClass="com.enterscript.noX3LanguagePlugin.language.psi.impl.parser.NOX3Parser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="NOX3"
  psiImplClassSuffix="Impl"
  psiPackage="com.enterscript.noX3LanguagePlugin.language.psi"
  psiImplPackage="com.enterscript.noX3LanguagePlugin.language.psi.impl"

  elementTypeHolderClass="com.enterscript.noX3LanguagePlugin.language.psi.NOX3Types"
  elementTypeClass="com.enterscript.noX3LanguagePlugin.language.psi.NOX3ElementType"
  tokenTypeClass="com.enterscript.noX3LanguagePlugin.language.psi.NOX3TokenType"

  psiImplUtilClass="com.enterscript.noX3LanguagePlugin.language.psi.impl.NOX3PsiImplUtil"
}

file ::= element_*

private element_ ::= (property | if_statement | for_statement | COMMENT | CRLF)

property ::= IDENTIFIER SEPARATOR value {
    mixin="com.enterscript.noX3LanguagePlugin.language.psi.impl.NOX3NamedElementImpl"
    implements="com.enterscript.noX3LanguagePlugin.language.psi.NOX3NamedElement"
    methods=[getKey getValue getName setName getNameIdentifier]
}

if_statement ::= IF expression CRLF element_* ENDIF

for_statement ::= FOR IDENTIFIER SEPARATOR expression TO expression CRLF element_* ENDFOR

value ::= expression

expression ::= NUMBER | STRING | IDENTIFIER
